spring.application.name=course-booking-api

spring.jpa.show-sql=true

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/booking
spring.datasource.username=root
spring.datasource.password=root

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=create
